In [1]:
from sklearn.preprocessing import LabelEncoder

items = ['apple', 'apple', 'banana', 'lemon', 'lemon', 'mango', 'orange', 'pear']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)

[0 0 1 2 2 3 4 5]


In [2]:
print(encoder.classes_)

['apple' 'banana' 'lemon' 'mango' 'orange' 'pear']


In [3]:
print(encoder.inverse_transform([2, 2, 0, 2, 1, 5, 4, 3, 3]))

['lemon' 'lemon' 'apple' 'lemon' 'banana' 'pear' 'orange' 'mango' 'mango']


In [4]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

labels = labels.reshape(-1, 1)
print(labels)

[[0]
 [0]
 [1]
 [2]
 [2]
 [3]
 [4]
 [5]]


In [5]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
(8, 6)


In [6]:
import pandas as pd

df = pd.DataFrame({'item': items})
df

item
0   apple
1   apple
2  banana
3   lemon
4   lemon
5   mango
6  orange
7    pear

In [7]:
pd.get_dummies(df)

item_apple  item_banana  item_lemon  item_mango  item_orange  item_pear
0           1            0           0           0            0          0
1           1            0           0           0            0          0
2           0            1           0           0            0          0
3           0            0           1           0            0          0
4           0            0           1           0            0          0
5           0            0           0           1            0          0
6           0            0           0           0            1          0
7           0            0           0           0            0          1

In [8]:
from sklearn.datasets import load_iris

iris =  load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

In [10]:
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature 들의 분산 값')
print(iris_df_scaled.var())

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [11]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

In [12]:
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 최소 값')
print(iris_df_scaled.min())
print('\nfeature 들의 최대 값')
print(iris_df_scaled.max())

feature 들의 최소 값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature 들의 최대 값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
