In [1]:
import numpy as np

In [2]:
list1 = [1, 2, 3]
print(list1, type(list1))

array1 = np.array(list1)
print(array1, type(array1))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [3]:
array1 = np.array([1, 2, 3])
print(array1, type(array1), array1.shape, array1.ndim)

array2 = np.array([[1, 2, 3]])
print(array2, type(array2), array2.shape, array2.ndim)

array3 = np.array([[1, 2, 3],
                  [2, 3, 4]])
print(array3, type(array3), array3.shape, array3.ndim)

[1 2 3] <class 'numpy.ndarray'> (3,) 1
[[1 2 3]] <class 'numpy.ndarray'> (1, 3) 2
[[1 2 3]
 [2 3 4]] <class 'numpy.ndarray'> (2, 3) 2


In [4]:
list1 = [1, 2, 3]
array1 = np.array(list1)
print(array1.dtype)

list2 = [1, 2, 'str']
array2 = np.array(list2)
print(array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3.dtype)

int32
<U11
float64


In [5]:
array_int = np.array([1, 2, 3])
print(array_int, array_int.dtype)

array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32
[1. 2. 3.] float64
[1 2 3] int32


In [6]:
array_float1 = np.array([1.1, 2.1, 3.1])
print(array_float1, array_float1.dtype)

array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1.1 2.1 3.1] float64
[1 2 3] int32


In [7]:
array2 = np.array([[1, 2, 3],
                  [2, 3, 4]])

print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

15
[3 5 7]
[6 9]


In [8]:
sequence_array = np.arange(10)
print(sequence_array, sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9] int32 (10,)


In [9]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array, zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]] int32 (3, 2)


In [10]:
one_array = np.ones((3, 2))
print(one_array, one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]] float64 (3, 2)


In [11]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(2, 5)
print(array2)
array3 = array1.reshape(5, 2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [12]:
array1 = np.arange(10)
print(array1, array1.shape)

array2 = array1.reshape(-1, 5)
print(array2, array2.shape)

array3 = array1.reshape(5, -1)
print(array3, array3.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)


In [13]:
array1 = np.arange(5)

array2d_1 = array1.reshape(-1, 1)
print(array2d_1, array2d_1.shape)

array1d = array2d_1.reshape(-1,)
print(array1d, array1d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]] (5, 1)
[0 1 2 3 4] (5,)


In [14]:
array1 = np.arange(start=1, stop=10)
print(array1)

print("array1[2] :", array1[2])
print(type(array1[2]))

print("array1[-1] :", array1[-1])
print("array1[-2] :", array1[-2])

[1 2 3 4 5 6 7 8 9]
array1[2] : 3
<class 'numpy.int32'>
array1[-1] : 9
array1[-2] : 8


In [15]:
array1[0] = 9
array1[8] = 0
print(array1)

[9 2 3 4 5 6 7 8 0]


In [16]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)
print("array2d[0, 0] :", array2d[0, 0])
print("array2d[0, 1] :", array2d[0, 1])
print("array2d[1, 0] :", array2d[1, 0])
print("array2d[2, 1] :", array2d[2, 1])
print("array2d[2, 2] :", array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0, 0] : 1
array2d[0, 1] : 2
array2d[1, 0] : 4
array2d[2, 1] : 8
array2d[2, 2] : 9


In [17]:
array1 = np.arange(start=1, stop=10)
print("array1 :", array1)

print("array1[0:3] :", array1[0:3])
print(type(array1[0:3]))

print("array1[:3] :", array1[:3])
print("array1[3:] :", array1[3:])
print("array1[:] :", array1[:])

array1 : [1 2 3 4 5 6 7 8 9]
array1[0:3] : [1 2 3]
<class 'numpy.ndarray'>
array1[:3] : [1 2 3]
array1[3:] : [4 5 6 7 8 9]
array1[:] : [1 2 3 4 5 6 7 8 9]


In [18]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print("array2d[0:2, 0:2]\n", array2d[0:2, 0:2])
print("array2d[1:3, 0:3]\n", array2d[1:3, 0:3])
print("array2d[1:3, :]\n", array2d[1:3, :])
print("array2d[:, :]\n", array2d[:, :])
print("array2d[:2, 1:]\n", array2d[:2, 1:])
print("array2d[:2, 0]\n", array2d[:2, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


In [19]:
print(array2d[[0, 1], 2])
print(array2d[[0, 1], 2].tolist())

print(array2d[[0, 2], 0:2])
print(array2d[[0, 2], 0:2].tolist())

print(array2d[[0, 1]])
print(array2d[[0, 1]].tolist())

[3 6]
[3, 6]
[[1 2]
 [7 8]]
[[1, 2], [7, 8]]
[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]


In [20]:
print(array1d > 5)
print(type(array1d > 5))

[False False False False False  True  True  True  True]
<class 'numpy.ndarray'>


In [21]:
print(array1d)
print("array1d[array1d > 5] :", array1d[array1d > 5])

[1 2 3 4 5 6 7 8 9]
array1d[array1d > 5] : [6 7 8 9]


In [22]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
print("array1d[boolean_indexes] :", array1d[boolean_indexes])

array1d[boolean_indexes] : [6 7 8 9]


In [23]:
target = []

for i in range(0, 9):
    if array1d[i] > 5:
        target.append(array1d[i])
        
print(np.array(target))

[6 7 8 9]


In [24]:
arr = np.array([4, 2, 8, 6, 5])
print(arr)

[4 2 8 6 5]


In [25]:
sort_arr1 = np.sort(arr)
print("sort_arr1 :", sort_arr1)
print("arr :", arr)

sort_arr1 : [2 4 5 6 8]
arr : [4 2 8 6 5]


In [26]:
sort_arr2 = arr.sort()
print(sort_arr2)
print(arr)

None
[2 4 5 6 8]


In [27]:
array2d = np.array([[9, 3, 4],
                  [5, 2, 10],
                   [6, 1, 9]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print(sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1)

[[ 5  1  4]
 [ 6  2  9]
 [ 9  3 10]]
[[ 3  4  9]
 [ 2  5 10]
 [ 1  6  9]]


In [28]:
arr = np.array([9, 5, 2, 1, 3])
print("arr :", arr)
print("np.sort(arr) :", np.sort(arr))

print("argsrt : ")
sort_indices = np.argsort(arr)
print(sort_indices)
print(type(sort_indices))

arr : [9 5 2 1 3]
np.sort(arr) : [1 2 3 5 9]
argsrt : 
[3 2 4 1 0]
<class 'numpy.ndarray'>


In [29]:
print(np.sort(arr)[::-1])
sort_indices_desc = np.argsort(arr)[::-1]
print(sort_indices_desc)

[9 5 3 2 1]
[0 1 4 2 3]


In [30]:
name_arr = np.array(['Kim', 'Lee', 'Park', 'Choi'])
score_arr = np.array([99, 75, 80, 79])

sort_indices = np.argsort(score_arr)
print(sort_indices)

name_arr_sort = name_arr[sort_indices]
score_arr_sort = score_arr[sort_indices]
print(name_arr_sort)
print(score_arr_sort)

[1 3 2 0]
['Lee' 'Choi' 'Park' 'Kim']
[75 79 80 99]


In [31]:
arr1 = np.array([[1, 2, 3],
             [4, 5, 6]])
arr2 = np.array([[7, 8],
             [9, 10],
             [11, 12]])

dot_product = np.dot(arr1, arr2)
print(dot_product)

[[ 58  64]
 [139 154]]


In [32]:
arr3 = np.array([[1, 2],
                [3, 4]])
transpose_mat = np.transpose(arr3)
print(transpose_mat)

[[1 3]
 [2 4]]
