In [1]:
text_sample_01 = 'He was an old man who fished alone in a skiff in the Gulf Stream and he had gone eighty-four days now without taking a fish. In the first forty days a boy had been with him. But after forty days without a fish the boy’s parents had told him that the old man was now definitely and finally salao, which is the worst form of unlucky, and the boy had gone at their orders in another boat which caught three good fish the first week. '
text_sample_02 = 'The old man was thin and gaunt with deep wrinkles in the back of his neck. The brown blotches of the benevolent skin cancer the sun brings from its reflection on the tropic sea were on his cheeks. The blotches ran well down the sides of his face and his hands had the deep-creased scars from handling heavy fish on the cords. But none of these scars were fresh. They were as old as erosions in a fishless desert.'
text = []
text.append(text_sample_01)
text.append(text_sample_02)
print(text, '\n', len(text))

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

cnt_vect = CountVectorizer()
cnt_vect.fit(text)

CountVectorizer()

In [3]:
ftr_vect = cnt_vect.transform(text)

In [4]:
print(type(ftr_vect), ftr_vect.shape)
print(ftr_vect)

<class 'scipy.sparse.csr.csr_matrix'> (2, 93)
  (0, 0)	1
  (0, 1)	1
  (0, 2)	1
  (0, 3)	3
  (0, 4)	1
  (0, 6)	1
  (0, 8)	1
  (0, 11)	1
  (0, 12)	3
  (0, 15)	1
  (0, 17)	1
  (0, 21)	3
  (0, 23)	1
  (0, 26)	1
  (0, 29)	1
  (0, 30)	2
  (0, 31)	3
  (0, 32)	1
  (0, 34)	1
  (0, 35)	2
  (0, 36)	1
  (0, 40)	2
  (0, 41)	1
  (0, 42)	1
  (0, 43)	4
  :	:
  (1, 50)	2
  (1, 52)	1
  (1, 53)	1
  (1, 54)	1
  (1, 55)	1
  (1, 57)	4
  (1, 58)	2
  (1, 59)	3
  (1, 62)	1
  (1, 63)	1
  (1, 65)	2
  (1, 66)	1
  (1, 67)	1
  (1, 69)	1
  (1, 71)	1
  (1, 74)	10
  (1, 76)	1
  (1, 77)	1
  (1, 78)	1
  (1, 81)	1
  (1, 83)	1
  (1, 85)	1
  (1, 86)	3
  (1, 89)	1
  (1, 92)	1


In [5]:
print(cnt_vect.vocabulary_)

{'he': 46, 'was': 83, 'an': 2, 'old': 58, 'man': 53, 'who': 88, 'fished': 32, 'alone': 1, 'in': 50, 'skiff': 68, 'the': 74, 'gulf': 42, 'stream': 70, 'and': 3, 'had': 43, 'gone': 40, 'eighty': 26, 'four': 36, 'days': 21, 'now': 56, 'without': 90, 'taking': 72, 'fish': 31, 'first': 30, 'forty': 35, 'boy': 12, 'been': 8, 'with': 89, 'him': 48, 'but': 15, 'after': 0, 'parents': 61, 'told': 80, 'that': 73, 'definitely': 23, 'finally': 29, 'salao': 64, 'which': 87, 'is': 51, 'worst': 91, 'form': 34, 'of': 57, 'unlucky': 82, 'at': 6, 'their': 75, 'orders': 60, 'another': 4, 'boat': 11, 'caught': 17, 'three': 79, 'good': 41, 'week': 84, 'thin': 78, 'gaunt': 39, 'deep': 22, 'wrinkles': 92, 'back': 7, 'his': 49, 'neck': 54, 'brown': 14, 'blotches': 10, 'benevolent': 9, 'skin': 69, 'cancer': 16, 'sun': 71, 'brings': 13, 'from': 38, 'its': 52, 'reflection': 63, 'on': 59, 'tropic': 81, 'sea': 66, 'were': 86, 'cheeks': 18, 'ran': 62, 'well': 85, 'down': 25, 'sides': 67, 'face': 28, 'hands': 45, 'cr

In [6]:
cnt_vect = CountVectorizer(max_features=5)
cnt_vect.fit(text)
ftr_vect = cnt_vect.transform(text)
print(type(ftr_vect), ftr_vect.shape)
print(cnt_vect.vocabulary_)

<class 'scipy.sparse.csr.csr_matrix'> (2, 5)
{'in': 2, 'the': 4, 'and': 0, 'had': 1, 'of': 3}


In [7]:
cnt_vect = CountVectorizer(max_features=5, stop_words='english')
cnt_vect.fit(text)
ftr_vect = cnt_vect.transform(text)
print(type(ftr_vect), ftr_vect.shape)
print(cnt_vect.vocabulary_)

<class 'scipy.sparse.csr.csr_matrix'> (2, 5)
{'old': 4, 'man': 3, 'days': 1, 'fish': 2, 'boy': 0}


In [8]:
cnt_vect = CountVectorizer(ngram_range=(1, 2))
cnt_vect.fit(text)
ftr_vect = cnt_vect.transform(text)
print(type(ftr_vect), ftr_vect.shape)
print(cnt_vect.vocabulary_)

<class 'scipy.sparse.csr.csr_matrix'> (2, 239)
{'he': 110, 'was': 213, 'an': 4, 'old': 147, 'man': 132, 'who': 227, 'fished': 77, 'alone': 2, 'in': 123, 'skiff': 170, 'the': 182, 'gulf': 99, 'stream': 174, 'and': 6, 'had': 101, 'gone': 94, 'eighty': 62, 'four': 85, 'days': 50, 'now': 139, 'without': 232, 'taking': 178, 'fish': 73, 'first': 70, 'forty': 83, 'boy': 30, 'been': 21, 'with': 229, 'him': 115, 'but': 37, 'after': 0, 'parents': 155, 'told': 207, 'that': 180, 'definitely': 57, 'finally': 68, 'salao': 161, 'which': 224, 'is': 128, 'worst': 235, 'form': 81, 'of': 142, 'unlucky': 211, 'at': 17, 'their': 197, 'orders': 153, 'another': 12, 'boat': 28, 'caught': 42, 'three': 205, 'good': 97, 'week': 217, 'he was': 112, 'was an': 214, 'an old': 5, 'old man': 149, 'man who': 134, 'who fished': 228, 'fished alone': 78, 'alone in': 3, 'in skiff': 126, 'skiff in': 171, 'in the': 127, 'the gulf': 191, 'gulf stream': 100, 'stream and': 175, 'and he': 9, 'he had': 111, 'had gone': 103, 'gone

In [9]:
cnt_vect = CountVectorizer(ngram_range=(1, 3))
cnt_vect.fit(text)
ftr_vect = cnt_vect.transform(text)
print(type(ftr_vect), ftr_vect.shape)
print(cnt_vect.vocabulary_)

<class 'scipy.sparse.csr.csr_matrix'> (2, 395)
{'he': 176, 'was': 353, 'an': 6, 'old': 242, 'man': 215, 'who': 376, 'fished': 123, 'alone': 3, 'in': 198, 'skiff': 280, 'the': 298, 'gulf': 157, 'stream': 286, 'and': 9, 'had': 160, 'gone': 149, 'eighty': 99, 'four': 135, 'days': 80, 'now': 227, 'without': 384, 'taking': 292, 'fish': 115, 'first': 111, 'forty': 131, 'boy': 48, 'been': 34, 'with': 379, 'him': 184, 'but': 60, 'after': 0, 'parents': 257, 'told': 344, 'that': 295, 'definitely': 92, 'finally': 108, 'salao': 266, 'which': 371, 'is': 209, 'worst': 389, 'form': 128, 'of': 232, 'unlucky': 350, 'at': 28, 'their': 329, 'orders': 254, 'another': 20, 'boat': 45, 'caught': 68, 'three': 341, 'good': 154, 'week': 360, 'he was': 179, 'was an': 354, 'an old': 7, 'old man': 245, 'man who': 219, 'who fished': 377, 'fished alone': 124, 'alone in': 4, 'in skiff': 203, 'skiff in': 281, 'in the': 205, 'the gulf': 317, 'gulf stream': 158, 'stream and': 287, 'and he': 14, 'he had': 177, 'had gone'

In [10]:
cnt_vect = CountVectorizer(ngram_range=(2, 2))
cnt_vect.fit(text)
ftr_vect = cnt_vect.transform(text)
print(type(ftr_vect), ftr_vect.shape)
print(cnt_vect.vocabulary_)

<class 'scipy.sparse.csr.csr_matrix'> (2, 146)
{'he was': 65, 'was an': 130, 'an old': 2, 'old man': 90, 'man who': 80, 'who fished': 139, 'fished alone': 45, 'alone in': 1, 'in skiff': 75, 'skiff in': 102, 'in the': 76, 'the gulf': 116, 'gulf stream': 57, 'stream and': 104, 'and he': 5, 'he had': 64, 'had gone': 59, 'gone eighty': 55, 'eighty four': 36, 'four days': 49, 'days now': 30, 'now without': 84, 'without taking': 143, 'taking fish': 106, 'fish in': 42, 'the first': 115, 'first forty': 40, 'forty days': 48, 'days boy': 29, 'boy had': 18, 'had been': 58, 'been with': 13, 'with him': 141, 'him but': 67, 'but after': 22, 'after forty': 0, 'days without': 31, 'without fish': 142, 'fish the': 44, 'the boy': 111, 'boy parents': 19, 'parents had': 94, 'had told': 61, 'told him': 127, 'him that': 68, 'that the': 107, 'the old': 117, 'man was': 79, 'was now': 131, 'now definitely': 83, 'definitely and': 34, 'and finally': 3, 'finally salao': 39, 'salao which': 97, 'which is': 138, 'is 

In [11]:
import numpy as np

dense = np.array([[3, 0, 1], [0, 2, 0]])

In [12]:
from scipy import sparse

data = np.array([3, 1, 2])

row_pos = np.array([0, 0, 1])
col_pos = np.array([0, 2, 1])

sparse_coo = sparse.coo_matrix((data, (row_pos, col_pos)))

In [13]:
print(type(sparse_coo))
print(sparse_coo)
dense01 = sparse_coo.toarray()
print(type(dense01), '\n', dense01)

<class 'scipy.sparse.coo.coo_matrix'>
  (0, 0)	3
  (0, 2)	1
  (1, 1)	2
<class 'numpy.ndarray'> 
 [[3 0 1]
 [0 2 0]]


In [14]:
dense2 = np.array([
    [0, 0, 1, 0, 0, 5],
    [1, 4, 0, 3, 2, 5],
    [2, 0, 0, 0, 0, 0],
    [0, 0, 0, 7, 0, 0],
    [1, 0, 0, 0, 0, 0],
])

data2 = np.array([1, 5, 1, 4, 3, 2, 5, 6, 3, 2, 7, 8, 1])

row_pos = np.array([0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 4, 4, 5])
col_pos = np.array([2, 5, 0, 1, 3, 4, 5, 1, 3, 0, 3, 5, 0])

sparse_coo = sparse.coo_matrix((data2, (row_pos, col_pos)))

row_pos_ind = np.array([0, 2, 7, 9, 10, 12, 13])

sparse_csr = sparse.csr_matrix((data2, col_pos, row_pos_ind))

print(sparse_coo.toarray())
print(sparse_csr.toarray())

[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [15]:
coo = sparse.coo_matrix(dense2)
csr = sparse.csr_matrix(dense2)

print(coo.toarray())
print(csr.toarray())

[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [2 0 0 0 0 0]
 [0 0 0 7 0 0]
 [1 0 0 0 0 0]]
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [2 0 0 0 0 0]
 [0 0 0 7 0 0]
 [1 0 0 0 0 0]]
